(()=>{
const FRAME_COUNT=15, CUT="#ff0000", GAS_URL="https://script.google.com/macros/s/AKfycby6-AzGmwUicIrD0hvWGzJgY6jUBXFOnigq9o6-KkS0ijxxqpjZIoc7rYmBglBxPjN8/exec";
const frameNames=["まる","しかく","六角形","八角形","ほし","ギザギザ","おはな","ふわふわ","おばけ","タグ","ハート","イカ","うさぎ","くま","ねこ"];
// 枠ごとのイニシャル下方向補正（mm）。40mmアートボード = 113.39 SVG単位。
const initialOffsetMm={5:1.5,7:1.5,13:6,14:1.5,15:2.5};
const initialOffsetY=frameNumber=>(initialOffsetMm[frameNumber]||0)*(113.39/40);
const palettes={透明系:[["クリア","#e8fbff"],["ピンク","#ffb8cc"],["レッド","#ff6673"],["オレンジ","#ffad65"],["イエロー","#ffe76c"],["グリーン","#72d6a1"],["ブルー","#62bceb"],["パープル","#ad87db"]],パステル系:[["桜","#f8c8d8"],["桃","#f4b5a5"],["ミルク","#fff5df"],["レモン","#f4e99d"],["ミント","#a8dec8"],["空","#a9d7ee"],["藤","#c7b6df"],["グレー","#c9c9c9"]],ビビッド系:[["赤","#e64248"],["橙","#f17c36"],["黄","#f2c230"],["黄緑","#84bd48"],["緑","#26966b"],["水色","#2caac4"],["青","#3561b6"],["紫","#7c47a6"],["黒","#333333"]]};
const $=id=>document.getElementById(id); let state={frame:1,letter:"A",category:"透明系",colorName:"クリア",color:"#e8fbff"};
function eventTag(){let d=new Date();return String(d.getMonth()+1).padStart(2,"0")+String(d.getDate()).padStart(2,"0")}
const device=new URLSearchParams(location.search).get("device")?.toUpperCase()||"X",key=`mi_ticket_${eventTag()}_${device}`;let count=+(localStorage.getItem(key)||0)+1;localStorage.setItem(key,count);function ticket(){return `${eventTag()}-${device}-${String(count).padStart(3,"0")}`}$('ticket').textContent=ticket();
function button(label,group,value,extra=""){let b=document.createElement("button");b.className=`choice ${extra}`;b.textContent=label;b.dataset.group=group;b.dataset.value=value;b.onclick=()=>select(group,value);return b}
frameNames.forEach((n,i)=>$('frames').append(button(n,"frame",i+1)));[..."ABCDEFGHIJKLMNOPQRSTUVWXYZ"].forEach(l=>$('letters').append(button(l,"letter",l)));
Object.keys(palettes).forEach(c=>{let b=document.createElement("button");b.textContent=c;b.onclick=()=>{state.category=c;renderColors();render()};$('colorTabs').append(b)});
function renderColors(){$('colors').replaceChildren();palettes[state.category].forEach(([n,c])=>{let b=button("","color",n,"color");b.title=n;b.style.background=c;b.dataset.hex=c;$('colors').append(b)})}
function select(group,value){if(group==="frame")state.frame=+value;else if(group==="letter")state.letter=value;else{let x=palettes[state.category].find(a=>a[0]===value);state.colorName=x[0];state.color=x[1]}render()}
async function asset(url){let r=await fetch(url);if(!r.ok)throw Error(url);return r.text()}
function mergeSvgs(frame,initial){let fp=new DOMParser().parseFromString(frame,"image/svg+xml"),lp=new DOMParser().parseFromString(initial,"image/svg+xml"),g=fp.createElementNS("http://www.w3.org/2000/svg","g");g.setAttribute("transform",`translate(0 ${initialOffsetY(state.frame).toFixed(3)})`);[...lp.documentElement.children].filter(n=>n.localName!=="defs").forEach(n=>g.append(n.cloneNode(true)));fp.documentElement.append(g);return new XMLSerializer().serializeToString(fp.documentElement)}
async function renderAsset(){try{let [f,l]=await Promise.all([asset(`assets/frames/frame-${String(state.frame).padStart(2,"0")}.svg`),asset(`assets/initials/style-1/${state.letter}.svg`)]),box=$('previewFrame');box.className="";box.style.color=state.color;box.innerHTML=mergeSvgs(f,l)}catch{let box=$('previewFrame');box.className="fallback-shape";box.innerHTML=`<span id="previewInitial">${state.letter}</span>`;box.style.color=state.color;box.style.borderColor=state.color}}
function render(){document.querySelectorAll('.choice').forEach(b=>b.setAttribute("aria-pressed",String((b.dataset.group==="frame"&&+b.dataset.value===state.frame)||(b.dataset.group==="letter"&&b.dataset.value===state.letter)||(b.dataset.group==="color"&&b.dataset.value===state.colorName))));document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.textContent===state.category));$('previewCharm').style.background=state.color;$('summary').textContent=`${frameNames[state.frame-1]}／${state.letter}／${state.colorName}`;renderAsset()}
function filename(ext){return `${ticket()}_${String(state.frame).padStart(2,"0")}_${state.letter}_${state.category}-${state.colorName}.${ext}`}
function cleanSvg(raw){let p=new DOMParser().parseFromString(raw,"image/svg+xml"),s=p.documentElement;s.querySelectorAll("text,image,use").forEach(n=>n.remove());s.querySelectorAll("path,circle,ellipse,rect,polygon,polyline,line").forEach(n=>{n.setAttribute("fill","none");n.setAttribute("stroke",CUT);n.setAttribute("stroke-width",n.getAttribute("stroke-width")||"0.2");n.setAttribute("vector-effect","non-scaling-stroke")});return new XMLSerializer().serializeToString(s)}
async function buildCutSvg(){let [f,l]=await Promise.all([asset(`assets/frames/frame-${String(state.frame).padStart(2,"0")}.svg`),asset(`assets/initials/style-1/${state.letter}.svg`)]),fp=new DOMParser().parseFromString(cleanSvg(f),"image/svg+xml"),lp=new DOMParser().parseFromString(cleanSvg(l),"image/svg+xml"),g=fp.createElementNS("http://www.w3.org/2000/svg","g");g.setAttribute("transform",`translate(0 ${initialOffsetY(state.frame).toFixed(3)})`);[...lp.documentElement.children].forEach(n=>g.append(n));fp.documentElement.append(g);fp.documentElement.insertAdjacentHTML("afterbegin",`<metadata>Cut lines: RGB 255,0,0 (#FF0000); initialOffsetY=${initialOffsetMm[state.frame]||0}mm; charm=${state.category}/${state.colorName}; ticket=${ticket()}</metadata>`);return new XMLSerializer().serializeToString(fp)}
function download(name,data,type){let a=document.createElement("a"),u=URL.createObjectURL(new Blob([data],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function proof(){return JSON.stringify({ticket:ticket(),frame:{number:state.frame,name:frameNames[state.frame-1]},initial:state.letter,charm:{category:state.category,name:state.colorName,previewColor:state.color},createdAt:new Date().toISOString()},null,2)}
function post(payload){return new Promise(ok=>{let i=document.createElement("iframe"),f=document.createElement("form"),x=document.createElement("input");i.name=`gas${Date.now()}`;i.hidden=true;f.method="POST";f.action=GAS_URL;f.target=i.name;x.name="payload";x.value=JSON.stringify(payload);f.append(x);document.body.append(i,f);f.submit();setTimeout(()=>{i.remove();f.remove();ok()},1500)})}
$('done').onclick=()=>{$('donePreview').innerHTML=$('preview').innerHTML;$('doneSummary').textContent=`${ticket()}　${$('summary').textContent}`;$('doneDialog').showModal()};$('edit').onclick=()=>$('doneDialog').close();
async function digest(s){let b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
$('unlock').onclick=async()=>{let ok=await digest($('staffPass').value)==="715d0a62f5ef1ff3341136b925d03f0676cc4a8d73986f9f7105e1a122c194ed";$('staffActions').hidden=!ok;$('status').textContent=ok?"スタッフ操作を表示しました":"合言葉が違います"};
$('downloadSvg').onclick=async()=>{try{download(filename("svg"),await buildCutSvg(),"image/svg+xml");$('status').textContent="加工用SVGを保存しました"}catch{$('status').textContent="正式な枠・イニシャルSVGを登録してください"}};$('downloadProof').onclick=()=>download(filename("json"),proof(),"application/json");$('sendDrive').onclick=async()=>{try{let svg=await buildCutSvg();await post({filename:filename("svg"),ticket:ticket(),svg,proof:JSON.parse(proof())});$('status').textContent="Driveへ送信しました"}catch(e){$('status').textContent=e.message}};$('next').onclick=()=>{count++;localStorage.setItem(key,count);location.reload()};renderColors();render();
})();
