(()=>{
const FRAME_COUNT=15, CUT="#ff0000", GAS_URL="https://script.google.com/macros/s/AKfycbwBtZlhcJoNTWGWdIJoXSb1cTIjkS-C5UMzRUWmDgbrp3R70rHxFbZgTx0bJ4y_lps7BA/exec";
const frameNames=["まる","しかく","六角形","八角形","ほし","とげとげ","おはな","もくもく","おばけ","タグ","ハート","イカ","うさぎ","くま","ねこ"];
const charms=[{key:"black",name:"ブラック",stock:7},{key:"blue",name:"ブルー",stock:10},{key:"green",name:"グリーン",stock:11},{key:"orange",name:"オレンジ",stock:10},{key:"pink",name:"ピンク",stock:9},{key:"purple",name:"パープル",stock:12},{key:"red",name:"レッド",stock:7},{key:"white",name:"ホワイト",stock:23},{key:"yellow",name:"イエロー",stock:8}];
// 枠ごとのイニシャル下方向補正（mm）。40mmアートボード = 113.39 SVG単位。
const initialOffsetMm={5:1.5,7:1.5,13:6,14:1.5,15:2.5};
const initialOffsetY=frameNumber=>(initialOffsetMm[frameNumber]||0)*(113.39/40);
const materials={
  "3mm厚 不透明板":[{name:"ホワイト ※半透明",color:"#ffffff"},{name:"ブラック",color:"#231916",stock:7},{name:"ブラウン",color:"#412311"},{name:"ネイビー",color:"#181c62"},{name:"ブルー",color:"#0f5fab",stock:6},{name:"ライトブルー",color:"#198bc1",stock:13},{name:"パープル",color:"#84216f",stock:7},{name:"ピンク",color:"#e85298"},{name:"オレンジ",color:"#df711b",stock:7},{name:"ライトオレンジ",color:"#eaa117",stock:3},{name:"フォレストグリーン",color:"#005734",stock:10},{name:"グリーン",color:"#16ae68",stock:4},{name:"ライトグリーン",color:"#52c83c"},{name:"パステルピンク（裏面マット）",color:"#f4b4d0"},{name:"ミルクティー（裏面マット）",color:"#d3c09c"},{name:"チョコレート（裏面マット）",color:"#7d4e47"},{name:"オフホワイト（裏面マット）",color:"#fdfce5"}],
  "3mm厚 クリア板":[{name:"クリア",color:"#e3e2e2"},{name:"クリアブラック",color:"#4a423f"},{name:"クリアパープル",color:"#76619b"},{name:"クリアグリーン",color:"#006b2d",stock:6}],
  "2mm厚 クリア板":[{name:"クリアネオンイエロー",color:"#dfff00"},{name:"クリアネオンオレンジ",color:"#ffb000"}]
};
Object.values(materials).flat().forEach(m=>{if(m.stock==null)m.stock=10});
const INVENTORY_KEY="mi_inventory_v1";
function inventoryId(type,category,name){return type==="material"?`material|${category}|${name}`:`charm|${name}`}
function initialInventory(){let result={};Object.entries(materials).forEach(([category,list])=>list.forEach(m=>result[inventoryId("material",category,m.name)]=m.stock));charms.forEach(c=>result[inventoryId("charm","",c.key)]=c.stock);return result}
function loadInventory(){try{return {...initialInventory(),...JSON.parse(localStorage.getItem(INVENTORY_KEY)||"{}")}}catch{return initialInventory()}}
let inventory=loadInventory();
function saveInventory(){localStorage.setItem(INVENTORY_KEY,JSON.stringify(inventory))}
function stockOf(type,category,name){return Math.max(0,Number(inventory[inventoryId(type,category,name)])||0)}
function stockLabel(n){return n===0?"売り切れ":n<=5?`残り${n}個`:"在庫あり"}
function materialOpacity(category,name){if(name==="クリア")return .08;if(name==="クリアグリーン")return .82;if(name==="クリアネオンイエロー")return .82;if(name==="クリアネオンオレンジ")return .86;if(name.includes("半透明"))return .68;if(category.includes("クリア板"))return .52;return 1}
const $=id=>document.getElementById(id); let state={frame:1,letter:"A",category:"3mm厚 クリア板",colorName:"クリア",color:"#e3e2e2",stock:null,opacity:.08,charmKey:"black",charmName:"ブラック"};
let previewMaskSeq=0;
function eventTag(){let d=new Date();return String(d.getMonth()+1).padStart(2,"0")+String(d.getDate()).padStart(2,"0")}
const device=new URLSearchParams(location.search).get("device")?.toUpperCase()||"X",key=`mi_ticket_${eventTag()}_${device}`;let count=+(localStorage.getItem(key)||0)+1;localStorage.setItem(key,count);function ticket(){return `${eventTag()}-${device}-${String(count).padStart(3,"0")}`}$('ticket').textContent=ticket();
function button(label,group,value,extra=""){let b=document.createElement("button");b.className=`choice ${extra}`;b.textContent=label;b.dataset.group=group;b.dataset.value=value;b.onclick=()=>select(group,value);return b}
frameNames.forEach((n,i)=>$('frames').append(button(n,"frame",i+1)));[..."ABCDEFGHIJKLMNOPQRSTUVWXYZ"].forEach(l=>$('letters').append(button(l,"letter",l)));
function renderCharms(){$('charms').replaceChildren();charms.forEach(c=>{let n=stockOf("charm","",c.key),b=button("","charm",c.key,"charm");b.disabled=n===0;b.innerHTML=`<img src="assets/markers/marker_${c.key}.svg" alt=""><span>${c.name}</span><small>${stockLabel(n)}</small>`;$('charms').append(b)})}
Object.keys(materials).forEach(c=>{let b=document.createElement("button");b.textContent=c;b.onclick=()=>{state.category=c;let first=materials[c].find(x=>x.stock!==0)||materials[c][0];Object.assign(state,{colorName:first.name,color:first.color,stock:first.stock??null,opacity:materialOpacity(c,first.name)});renderColors();render()};$('colorTabs').append(b)});
function renderColors(){$('colors').replaceChildren();materials[state.category].forEach(m=>{let opacity=materialOpacity(state.category,m.name),n=stockOf("material",state.category,m.name),b=button("","color",m.name,"color");b.disabled=n===0;b.dataset.hex=m.color;b.innerHTML=`<span class="swatch${opacity<1?" is-clear":""}" style="--swatch-color:${m.color};--swatch-opacity:${opacity}"></span><span class="color-copy"><strong>${m.name}</strong><small>${stockLabel(n)}${opacity<1?"・透明素材":""}</small></span>`;$('colors').append(b)})}
function select(group,value){if(group==="frame")state.frame=+value;else if(group==="letter")state.letter=value;else if(group==="charm"){let x=charms.find(a=>a.key===value);Object.assign(state,{charmKey:x.key,charmName:x.name})}else{let x=materials[state.category].find(a=>a.name===value);Object.assign(state,{colorName:x.name,color:x.color,stock:x.stock??null,opacity:materialOpacity(state.category,x.name)})}render()}
async function asset(url){let r=await fetch(url);if(!r.ok)throw Error(url);return r.text()}
function previewSvg(frame,initial){
  const ns="http://www.w3.org/2000/svg",seq=++previewMaskSeq,maskId=`materialMask${seq}`,outlineId=`clearOutline${seq}`,isClear=state.category.includes("クリア板"),fp=new DOMParser().parseFromString(frame,"image/svg+xml"),lp=new DOMParser().parseFromString(initial,"image/svg+xml"),svg=document.createElementNS(ns,"svg"),defs=document.createElementNS(ns,"defs"),mask=document.createElementNS(ns,"mask"),outer=document.createElementNS(ns,"g"),cuts=document.createElementNS(ns,"g"),letters=document.createElementNS(ns,"g"),material=document.createElementNS(ns,"g"),rect=document.createElementNS(ns,"rect");
  svg.setAttribute("viewBox","0 0 113.39 113.39");mask.id=maskId;mask.setAttribute("maskUnits","userSpaceOnUse");mask.setAttribute("x","0");mask.setAttribute("y","0");mask.setAttribute("width","113.39");mask.setAttribute("height","113.39");
  [...fp.documentElement.children].filter(n=>n.localName!=="defs").forEach(n=>{let c=n.cloneNode(true),isHole=c.localName==="circle"&&Number(c.getAttribute("r"))<5;c.removeAttribute("class");c.removeAttribute("style");c.setAttribute("stroke","none");c.setAttribute("fill",isHole?"black":"white");(isHole?cuts:outer).append(c)});
  letters.setAttribute("transform",`translate(0 ${initialOffsetY(state.frame).toFixed(3)})`);[...lp.documentElement.children].filter(n=>n.localName!=="defs").forEach(n=>{let c=n.cloneNode(true);c.removeAttribute("class");c.removeAttribute("style");c.setAttribute("stroke","none");c.setAttribute("fill","black");letters.append(c)});
  mask.append(outer,cuts,letters);defs.append(mask);
  if(isClear)defs.insertAdjacentHTML("beforeend",`<filter id="${outlineId}" x="-5%" y="-5%" width="110%" height="110%" color-interpolation-filters="sRGB"><feMorphology in="SourceAlpha" operator="dilate" radius="0.42" result="expanded"/><feComposite in="expanded" in2="SourceAlpha" operator="out" result="outline"/><feFlood flood-color="#514b48" flood-opacity="0.82" result="outlineColor"/><feComposite in="outlineColor" in2="outline" operator="in"/></filter>`);
  rect.setAttribute("width","113.39");rect.setAttribute("height","113.39");rect.setAttribute("fill",state.color);rect.setAttribute("fill-opacity",String(state.opacity));rect.setAttribute("mask",`url(#${maskId})`);
  if(isClear){let outlineMaterial=document.createElementNS(ns,"g"),outlineRect=rect.cloneNode();outlineRect.setAttribute("fill","#000");outlineRect.setAttribute("fill-opacity","1");outlineMaterial.append(outlineRect);outlineMaterial.setAttribute("filter",`url(#${outlineId})`);svg.append(defs,outlineMaterial)}else svg.append(defs);
  material.append(rect);svg.append(material);return new XMLSerializer().serializeToString(svg)
}
async function renderAsset(){try{let [f,l]=await Promise.all([asset(`assets/frames/frame-${String(state.frame).padStart(2,"0")}.svg`),asset(`assets/initials/style-1/${state.letter}.svg`)]),box=$('previewFrame');box.className=`material-preview${state.category.includes("クリア板")?" is-clear-material":""}`;box.style.color="";box.innerHTML=previewSvg(f,l)}catch{let box=$('previewFrame');box.className="fallback-shape";box.innerHTML=`<span id="previewInitial">${state.letter}</span>`;box.style.background=state.color}}
function render(){document.querySelectorAll('.choice').forEach(b=>b.setAttribute("aria-pressed",String((b.dataset.group==="frame"&&+b.dataset.value===state.frame)||(b.dataset.group==="letter"&&b.dataset.value===state.letter)||(b.dataset.group==="color"&&b.dataset.value===state.colorName)||(b.dataset.group==="charm"&&b.dataset.value===state.charmKey))));document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.textContent===state.category));$('previewCharm').src=`assets/markers/marker_${state.charmKey}.svg`;$('summary').textContent=`${frameNames[state.frame-1]}／${state.letter}／${state.category}・${state.colorName}／チャーム：${state.charmName}`;renderAsset()}
function nickname(){return $('nickname').value.normalize("NFKC").trim().replace(/[\\/:*?"<>|]/g,"").replace(/\s+/g,"-").slice(0,20)}
function filename(ext){return `${ticket()}-${nickname()}_${String(state.frame).padStart(2,"0")}${frameNames[state.frame-1]}_${state.letter}_${state.colorName}_チャーム${state.charmName}.${ext}`}
function previewFilename(){return filename("svg").replace(/\.svg$/,"_preview.svg")}
function cleanSvg(raw){let p=new DOMParser().parseFromString(raw,"image/svg+xml"),s=p.documentElement;s.querySelectorAll("text,image,use").forEach(n=>n.remove());s.querySelectorAll("path,circle,ellipse,rect,polygon,polyline,line").forEach(n=>{n.setAttribute("fill","none");n.setAttribute("stroke",CUT);n.setAttribute("stroke-width",n.getAttribute("stroke-width")||"0.2");n.setAttribute("vector-effect","non-scaling-stroke")});return new XMLSerializer().serializeToString(s)}
async function buildCutSvg(){let [f,l]=await Promise.all([asset(`assets/frames/frame-${String(state.frame).padStart(2,"0")}.svg`),asset(`assets/initials/style-1/${state.letter}.svg`)]),fp=new DOMParser().parseFromString(cleanSvg(f),"image/svg+xml"),lp=new DOMParser().parseFromString(cleanSvg(l),"image/svg+xml"),g=fp.createElementNS("http://www.w3.org/2000/svg","g");g.setAttribute("transform",`translate(0 ${initialOffsetY(state.frame).toFixed(3)})`);[...lp.documentElement.children].forEach(n=>g.append(n));fp.documentElement.append(g);fp.documentElement.insertAdjacentHTML("afterbegin",`<metadata>Cut lines: RGB 255,0,0 (#FF0000); initialOffsetY=${initialOffsetMm[state.frame]||0}mm; material=${state.category}/${state.colorName}; charm=${state.charmName}; ticket=${ticket()}</metadata>`);return new XMLSerializer().serializeToString(fp)}
function xmlText(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]))}
async function buildPreviewSvg(){let [f,l,charm]=await Promise.all([asset(`assets/frames/frame-${String(state.frame).padStart(2,"0")}.svg`),asset(`assets/initials/style-1/${state.letter}.svg`),asset(`assets/markers/marker_${state.charmKey}.svg`)]),inner=new DOMParser().parseFromString(previewSvg(f,l),"image/svg+xml").documentElement.innerHTML,charmImage=new DOMParser().parseFromString(charm,"image/svg+xml").querySelector("image")?.getAttribute("href")||"",shape=`${String(state.frame).padStart(2,"0")}${frameNames[state.frame-1]}／${state.letter}`,material=`${state.category}・${state.colorName}`,charmText=`チャーム：${state.charmName}`;return `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="780" viewBox="0 0 600 780"><defs><pattern id="checker" width="24" height="24" patternUnits="userSpaceOnUse"><rect width="24" height="24" fill="#f8f5ef"/><rect width="12" height="12" fill="#e9e4dc"/><rect x="12" y="12" width="12" height="12" fill="#e9e4dc"/></pattern></defs><rect width="600" height="780" rx="34" fill="#fff"/><rect x="30" y="30" width="540" height="500" rx="28" fill="url(#checker)"/><g transform="translate(96 76) scale(3.6)">${inner}</g><rect x="468" y="48" width="82" height="126" rx="12" fill="#fff" stroke="#e4dfd8"/><image x="472" y="52" width="74" height="118" preserveAspectRatio="xMidYMid slice" href="${charmImage}"/><g font-family="system-ui,-apple-system,'Noto Sans JP',sans-serif" fill="#302b29"><path d="M30 604H570M30 674H570" stroke="#e6e1dc"/><text x="40" y="575" font-size="18" fill="#8a7770">受付番号</text><text x="560" y="575" font-size="18" text-anchor="end">${xmlText(ticket())}</text><text x="40" y="645" font-size="18" fill="#8a7770">ニックネーム</text><text x="560" y="645" font-size="18" text-anchor="end">${xmlText(nickname())}</text><text x="40" y="712" font-size="18" fill="#8a7770">えらんだもの</text><text x="180" y="704" font-size="18">${xmlText(shape)}</text><text x="180" y="732" font-size="16">${xmlText(material)}</text><text x="180" y="758" font-size="16">${xmlText(charmText)}</text></g></svg>`}
function download(name,data,type){let a=document.createElement("a"),u=URL.createObjectURL(new Blob([data],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function proof(){return JSON.stringify({ticket:ticket(),nickname:nickname(),frame:{number:state.frame,name:frameNames[state.frame-1]},initial:state.letter,material:{key:`${state.category}｜${state.colorName}`,category:state.category,name:state.colorName,previewColor:state.color,previewOpacity:state.opacity,initialStock:state.stock},charm:{key:state.charmKey,name:state.charmName},createdAt:new Date().toISOString()},null,2)}
function post(payload){return new Promise(ok=>{let i=document.createElement("iframe"),f=document.createElement("form"),x=document.createElement("input");i.name=`gas${Date.now()}`;i.hidden=true;f.method="POST";f.action=GAS_URL;f.target=i.name;x.name="payload";x.value=JSON.stringify(payload);f.append(x);document.body.append(i,f);f.submit();setTimeout(()=>{i.remove();f.remove();ok()},1500)})}
function getFromGas(params={}){return new Promise((resolve,reject)=>{let cb=`miGas${Date.now()}${Math.random().toString(36).slice(2)}`,s=document.createElement("script"),timer=setTimeout(()=>finish(Error("在庫情報を取得できませんでした")),7000);function finish(err,value){clearTimeout(timer);delete window[cb];s.remove();err?reject(err):resolve(value)}window[cb]=value=>finish(null,value);s.onerror=()=>finish(Error("在庫情報を取得できませんでした"));s.src=`${GAS_URL}?${new URLSearchParams({...params,callback:cb,_:Date.now()})}`;document.body.append(s)})}
async function syncInventory(){try{let data=await getFromGas({action:"inventory"});if(data.ok&&data.inventory){inventory={...initialInventory(),...data.inventory};saveInventory();renderColors();renderCharms();renderInventory();render()}}catch(e){console.warn(e.message)}}
function renderInventory(){
  let root=$('inventory');if(!root)return;root.replaceChildren();
  const addGroup=(title,rows)=>{let section=document.createElement("section");section.className="inventory-group";section.innerHTML=`<h4>${title}</h4>`;rows.forEach(row=>{let n=stockOf(row.type,row.category,row.key),line=document.createElement("div");line.className="inventory-row";line.innerHTML=`<span>${row.name}</span><output>${n}</output><button type="button" aria-label="${row.name}を1個減らす" ${n===0?"disabled":""}>－</button><button type="button" aria-label="${row.name}を1個増やす">＋</button>`;let buttons=line.querySelectorAll("button");buttons[0].onclick=()=>adjustInventory(row,-1);buttons[1].onclick=()=>adjustInventory(row,1);section.append(line)});root.append(section)};
  Object.entries(materials).forEach(([category,list])=>addGroup(category,list.map(m=>({type:"material",category,key:m.name,name:m.name}))));
  addGroup("チャーム",charms.map(c=>({type:"charm",category:"",key:c.key,name:c.name})));
}
async function adjustInventory(item,delta){let id=inventoryId(item.type,item.category,item.key),before=stockOf(item.type,item.category,item.key);inventory[id]=Math.max(0,before+delta);saveInventory();renderColors();renderCharms();renderInventory();render();$('status').textContent="在庫を更新しています…";try{await post({action:"inventoryAdjust",id,delta,staffPass:$('staffPass').value});await syncInventory();$('status').textContent=`${item.name}の在庫を${stockOf(item.type,item.category,item.key)}個に変更しました`}catch(e){inventory[id]=before;saveInventory();renderColors();renderCharms();renderInventory();$('status').textContent=e.message}}
function updateNicknamePreview(){$('nicknamePreview').textContent=nickname()||"未入力"}
$('nickname').addEventListener("input",updateNicknamePreview);$('nickname').addEventListener("change",updateNicknamePreview);$('nickname').addEventListener("keyup",updateNicknamePreview);
$('done').onclick=()=>{if(!nickname()){$('nickname').setCustomValidity("ニックネームを入力してください");$('nickname').reportValidity();$('nickname').focus();return}$('nickname').setCustomValidity("");$('donePreview').innerHTML=$('preview').innerHTML;$('doneSummary').textContent=`${ticket()}　${nickname()}　${$('summary').textContent}`;$('doneDialog').showModal()};$('edit').onclick=()=>$('doneDialog').close();
async function digest(s){let b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
$('unlock').onclick=async()=>{let ok=await digest($('staffPass').value)==="715d0a62f5ef1ff3341136b925d03f0676cc4a8d73986f9f7105e1a122c194ed";$('staffActions').hidden=!ok;if(ok)renderInventory();$('status').textContent=ok?"スタッフ操作を表示しました":"合言葉が違います"};
$('downloadSvg').onclick=async()=>{try{download(filename("svg"),await buildCutSvg(),"image/svg+xml");$('status').textContent="加工用SVGを端末に保存しました"}catch{$('status').textContent="正式な枠・イニシャルSVGを登録してください"}};$('downloadPreview').onclick=async()=>{try{download(previewFilename(),await buildPreviewSvg(),"image/svg+xml");$('status').textContent="プレビュー画像を端末に保存しました"}catch(e){$('status').textContent=e.message}};$('downloadProof').onclick=()=>download(filename("json"),proof(),"application/json");$('sendDrive').onclick=async()=>{try{if(stockOf("material",state.category,state.colorName)===0||stockOf("charm","",state.charmKey)===0)throw Error("選択した材料が売り切れです。選び直してください");let savedKey=`mi_saved_${ticket()}`;if(localStorage.getItem(savedKey))throw Error("この受付番号は保存済みです");let svg=await buildCutSvg(),materialId=inventoryId("material",state.category,state.colorName),charmId=inventoryId("charm","",state.charmKey);$('status').textContent="Driveへ保存しています…";await post({action:"saveOrder",filename:filename("svg"),ticket:ticket(),svg,materialId,charmId,proof:JSON.parse(proof()),staffPass:$('staffPass').value});await syncInventory();let result=await getFromGas({action:"status",ticket:ticket()});if(!result.ok)throw Error(result.message||"保存結果を確認できませんでした");localStorage.setItem(savedKey,"1");$('status').textContent="加工用SVGをDriveへ保存し、在庫を各1個減らしました"}catch(e){$('status').textContent=e.message}};$('next').onclick=()=>{count++;localStorage.setItem(key,count);location.reload()};renderColors();renderCharms();render();syncInventory();
})();
