(()=>{
const FRAME_COUNT=15, CUT="#ff0000", GAS_URL="https://script.google.com/macros/s/AKfycby6-AzGmwUicIrD0hvWGzJgY6jUBXFOnigq9o6-KkS0ijxxqpjZIoc7rYmBglBxPjN8/exec";
const frameNames=["まる","しかく","六角形","八角形","ほし","ギザギザ","おはな","ふわふわ","おばけ","タグ","ハート","イカ","うさぎ","くま","ねこ"];
// 枠ごとのイニシャル下方向補正（mm）。40mmアートボード = 113.39 SVG単位。
const initialOffsetMm={5:1.5,7:1.5,13:6,14:1.5,15:2.5};
const initialOffsetY=frameNumber=>(initialOffsetMm[frameNumber]||0)*(113.39/40);
const materials={
  "3mm厚 クリア板":[{name:"クリア",color:"#dff7f7"},{name:"クリアブラック",color:"#596064"},{name:"クリアパープル",color:"#9b7bc5"},{name:"クリアグリーン",color:"#66b98b",stock:6}],
  "3mm厚 不透明板":[{name:"ホワイト ※半透明",color:"#f2f1e9"},{name:"ブラック",color:"#252525",stock:7},{name:"ブラウン",color:"#704936"},{name:"ネイビー",color:"#273b58"},{name:"ブルー",color:"#2471b8",stock:6},{name:"ライトブルー",color:"#7fc7e7",stock:13},{name:"パープル",color:"#8055a7",stock:7},{name:"ピンク",color:"#e789ac"},{name:"オレンジ",color:"#ea7435",stock:7},{name:"ライトオレンジ",color:"#f4ad72",stock:3},{name:"フォレストグリーン",color:"#315e46",stock:10},{name:"グリーン",color:"#3e9864",stock:4},{name:"ライトグリーン",color:"#9dcf91"},{name:"パステルピンク（裏面マット）",color:"#edb7c4"},{name:"ミルクティー（裏面マット）",color:"#c9ad8d"},{name:"チョコレート（裏面マット）",color:"#64463a"},{name:"オフホワイト（裏面マット）",color:"#eee8d9"}],
  "2mm厚 クリア板":[{name:"クリアネオンイエロー",color:"#e5f43b"},{name:"クリアネオンオレンジ",color:"#ff8a32"}]
};
const $=id=>document.getElementById(id); let state={frame:1,letter:"A",category:"3mm厚 クリア板",colorName:"クリア",color:"#dff7f7",stock:null};
let previewMaskSeq=0;
function eventTag(){let d=new Date();return String(d.getMonth()+1).padStart(2,"0")+String(d.getDate()).padStart(2,"0")}
const device=new URLSearchParams(location.search).get("device")?.toUpperCase()||"X",key=`mi_ticket_${eventTag()}_${device}`;let count=+(localStorage.getItem(key)||0)+1;localStorage.setItem(key,count);function ticket(){return `${eventTag()}-${device}-${String(count).padStart(3,"0")}`}$('ticket').textContent=ticket();
function button(label,group,value,extra=""){let b=document.createElement("button");b.className=`choice ${extra}`;b.textContent=label;b.dataset.group=group;b.dataset.value=value;b.onclick=()=>select(group,value);return b}
frameNames.forEach((n,i)=>$('frames').append(button(n,"frame",i+1)));[..."ABCDEFGHIJKLMNOPQRSTUVWXYZ"].forEach(l=>$('letters').append(button(l,"letter",l)));
Object.keys(materials).forEach(c=>{let b=document.createElement("button");b.textContent=c;b.onclick=()=>{state.category=c;let first=materials[c].find(x=>x.stock!==0)||materials[c][0];Object.assign(state,{colorName:first.name,color:first.color,stock:first.stock??null});renderColors();render()};$('colorTabs').append(b)});
function renderColors(){$('colors').replaceChildren();materials[state.category].forEach(m=>{let b=button("","color",m.name,"color");b.disabled=m.stock===0;b.dataset.hex=m.color;b.innerHTML=`<span class="swatch" style="background:${m.color}"></span><span class="color-copy"><strong>${m.name}</strong><small>${m.stock===0?"売り切れ":m.stock!=null?`残り${m.stock}`:"在庫あり"}</small></span>`;$('colors').append(b)})}
function select(group,value){if(group==="frame")state.frame=+value;else if(group==="letter")state.letter=value;else{let x=materials[state.category].find(a=>a.name===value);Object.assign(state,{colorName:x.name,color:x.color,stock:x.stock??null})}render()}
async function asset(url){let r=await fetch(url);if(!r.ok)throw Error(url);return r.text()}
function previewSvg(frame,initial){const ns="http://www.w3.org/2000/svg",maskId=`materialMask${++previewMaskSeq}`,fp=new DOMParser().parseFromString(frame,"image/svg+xml"),lp=new DOMParser().parseFromString(initial,"image/svg+xml"),svg=document.createElementNS(ns,"svg"),defs=document.createElementNS(ns,"defs"),mask=document.createElementNS(ns,"mask"),outer=document.createElementNS(ns,"g"),cuts=document.createElementNS(ns,"g"),letters=document.createElementNS(ns,"g"),rect=document.createElementNS(ns,"rect");svg.setAttribute("viewBox","0 0 113.39 113.39");mask.id=maskId;mask.setAttribute("maskUnits","userSpaceOnUse");mask.setAttribute("x","0");mask.setAttribute("y","0");mask.setAttribute("width","113.39");mask.setAttribute("height","113.39");[...fp.documentElement.children].filter(n=>n.localName!=="defs").forEach(n=>{let c=n.cloneNode(true),isHole=c.localName==="circle"&&Number(c.getAttribute("r"))<5;c.removeAttribute("class");c.removeAttribute("style");c.setAttribute("stroke","none");c.setAttribute("fill",isHole?"black":"white");(isHole?cuts:outer).append(c)});letters.setAttribute("transform",`translate(0 ${initialOffsetY(state.frame).toFixed(3)})`);[...lp.documentElement.children].filter(n=>n.localName!=="defs").forEach(n=>{let c=n.cloneNode(true);c.removeAttribute("class");c.removeAttribute("style");c.setAttribute("stroke","none");c.setAttribute("fill","black");letters.append(c)});mask.append(outer,cuts,letters);defs.append(mask);rect.setAttribute("width","113.39");rect.setAttribute("height","113.39");rect.setAttribute("fill",state.color);rect.setAttribute("mask",`url(#${maskId})`);svg.append(defs,rect);return new XMLSerializer().serializeToString(svg)}
async function renderAsset(){try{let [f,l]=await Promise.all([asset(`assets/frames/frame-${String(state.frame).padStart(2,"0")}.svg`),asset(`assets/initials/style-1/${state.letter}.svg`)]),box=$('previewFrame');box.className="material-preview";box.style.color="";box.innerHTML=previewSvg(f,l)}catch{let box=$('previewFrame');box.className="fallback-shape";box.innerHTML=`<span id="previewInitial">${state.letter}</span>`;box.style.background=state.color}}
function render(){document.querySelectorAll('.choice').forEach(b=>b.setAttribute("aria-pressed",String((b.dataset.group==="frame"&&+b.dataset.value===state.frame)||(b.dataset.group==="letter"&&b.dataset.value===state.letter)||(b.dataset.group==="color"&&b.dataset.value===state.colorName))));document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.textContent===state.category));$('previewCharm').style.display="none";$('summary').textContent=`${frameNames[state.frame-1]}／${state.letter}／${state.category}・${state.colorName}`;renderAsset()}
function filename(ext){return `${ticket()}_${String(state.frame).padStart(2,"0")}_${state.letter}_${state.category}-${state.colorName}.${ext}`}
function cleanSvg(raw){let p=new DOMParser().parseFromString(raw,"image/svg+xml"),s=p.documentElement;s.querySelectorAll("text,image,use").forEach(n=>n.remove());s.querySelectorAll("path,circle,ellipse,rect,polygon,polyline,line").forEach(n=>{n.setAttribute("fill","none");n.setAttribute("stroke",CUT);n.setAttribute("stroke-width",n.getAttribute("stroke-width")||"0.2");n.setAttribute("vector-effect","non-scaling-stroke")});return new XMLSerializer().serializeToString(s)}
async function buildCutSvg(){let [f,l]=await Promise.all([asset(`assets/frames/frame-${String(state.frame).padStart(2,"0")}.svg`),asset(`assets/initials/style-1/${state.letter}.svg`)]),fp=new DOMParser().parseFromString(cleanSvg(f),"image/svg+xml"),lp=new DOMParser().parseFromString(cleanSvg(l),"image/svg+xml"),g=fp.createElementNS("http://www.w3.org/2000/svg","g");g.setAttribute("transform",`translate(0 ${initialOffsetY(state.frame).toFixed(3)})`);[...lp.documentElement.children].forEach(n=>g.append(n));fp.documentElement.append(g);fp.documentElement.insertAdjacentHTML("afterbegin",`<metadata>Cut lines: RGB 255,0,0 (#FF0000); initialOffsetY=${initialOffsetMm[state.frame]||0}mm; material=${state.category}/${state.colorName}; ticket=${ticket()}</metadata>`);return new XMLSerializer().serializeToString(fp)}
function download(name,data,type){let a=document.createElement("a"),u=URL.createObjectURL(new Blob([data],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function proof(){return JSON.stringify({ticket:ticket(),frame:{number:state.frame,name:frameNames[state.frame-1]},initial:state.letter,material:{key:`${state.category}｜${state.colorName}`,category:state.category,name:state.colorName,previewColor:state.color,initialStock:state.stock},createdAt:new Date().toISOString()},null,2)}
function post(payload){return new Promise(ok=>{let i=document.createElement("iframe"),f=document.createElement("form"),x=document.createElement("input");i.name=`gas${Date.now()}`;i.hidden=true;f.method="POST";f.action=GAS_URL;f.target=i.name;x.name="payload";x.value=JSON.stringify(payload);f.append(x);document.body.append(i,f);f.submit();setTimeout(()=>{i.remove();f.remove();ok()},1500)})}
$('done').onclick=()=>{$('donePreview').innerHTML=$('preview').innerHTML;$('doneSummary').textContent=`${ticket()}　${$('summary').textContent}`;$('doneDialog').showModal()};$('edit').onclick=()=>$('doneDialog').close();
async function digest(s){let b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
$('unlock').onclick=async()=>{let ok=await digest($('staffPass').value)==="715d0a62f5ef1ff3341136b925d03f0676cc4a8d73986f9f7105e1a122c194ed";$('staffActions').hidden=!ok;$('status').textContent=ok?"スタッフ操作を表示しました":"合言葉が違います"};
$('downloadSvg').onclick=async()=>{try{download(filename("svg"),await buildCutSvg(),"image/svg+xml");$('status').textContent="加工用SVGを保存しました"}catch{$('status').textContent="正式な枠・イニシャルSVGを登録してください"}};$('downloadProof').onclick=()=>download(filename("json"),proof(),"application/json");$('sendDrive').onclick=async()=>{try{let svg=await buildCutSvg();await post({filename:filename("svg"),ticket:ticket(),svg,proof:JSON.parse(proof())});$('status').textContent="Driveへ送信しました"}catch(e){$('status').textContent=e.message}};$('next').onclick=()=>{count++;localStorage.setItem(key,count);location.reload()};renderColors();render();
})();
